const DEFAULT_EVENTS = [
    {
        id: 1,
        title: "횡성 호수길 축제",
        category: "체험",
        region: "횡성군",
        address: "횡성호수길 일원",
        startDate: "2026-06-07",
        endDate: "2026-06-07",
        time: "13:00~18:00",
        price: "무료",
        image: "resources/lake-festival.png",
        description: "횡성호를 따라 걷는 산책 코스와 지역 체험 프로그램을 함께 즐길 수 있는 호수길 축제입니다.",
        transportInfo: "횡성시외버스터미널에서 행사장 방면 버스 또는 택시 이용 가능",
        parkingInfo: "행사장 인근 임시 주차장 및 공영주차장 이용 가능",
        nearbyStores: ["횡성 한우 식당가", "로컬 카페", "농특산물 판매장"],
        applyLink: "#",
        contact: "033-000-0000",
        latitude: 37.4816,
        longitude: 128.0842,
        status: "approved"
    },
    {
        id: 2,
        title: "성북 골목 음식 축제",
        category: "무료 행사",
        region: "서울 성북구",
        address: "성북천 분수광장",
        startDate: "2026-06-08",
        endDate: "2026-06-09",
        time: "11:00~20:00",
        price: "무료",
        image: "resources/seongbuk-food-festival.png",
        description: "동네 식당과 주민 셀러가 참여하는 작은 먹거리 행사입니다.",
        transportInfo: "한성대입구역 2번 출구 도보 8분",
        parkingInfo: "행사장 내 주차 불가, 공영주차장 이용 권장",
        nearbyStores: ["분식 골목", "로컬 카페", "베이커리"],
        applyLink: "#",
        contact: "02-111-2222",
        latitude: 37.5894,
        longitude: 127.0082,
        status: "approved"
    },
    {
        id: 3,
        title: "전주 생활문화 공연",
        category: "공연",
        region: "전주시",
        address: "전주한옥마을 소공연장",
        startDate: "2026-06-10",
        endDate: "2026-06-10",
        time: "17:00~19:00",
        price: "무료",
        image: "resources/jeunju-festival.jpg",
        description: "지역 예술인이 참여하는 생활문화 음악 공연입니다.",
        transportInfo: "전주역에서 버스 79번 이용, 한옥마을 정류장 하차",
        parkingInfo: "한옥마을 공영주차장 유료 이용",
        nearbyStores: ["한옥마을 상점가", "전통찻집", "기념품점"],
        applyLink: "#",
        contact: "063-111-3333",
        latitude: 35.8151,
        longitude: 127.1534,
        status: "approved"
    },
    {
        id: 4,
        title: "양평 강변 체험 마당",
        category: "체험",
        region: "양평군",
        address: "양평 물맑은시장 앞 광장",
        startDate: "2026-06-12",
        endDate: "2026-06-12",
        time: "10:00~16:00",
        price: "5,000원",
        image: "resources/yangpeung-festival.jpg",
        description: "가족 단위 방문객을 위한 공예, 농산물 체험 프로그램입니다.",
        transportInfo: "양평역 도보 12분",
        parkingInfo: "시장 공영주차장 2시간 무료",
        nearbyStores: ["전통시장", "로컬 푸드 매장", "강변 산책로"],
        applyLink: "#",
        contact: "031-111-4444",
        latitude: 37.4919,
        longitude: 127.4873,
        status: "approved"
    },
    {
        id: 5,
        title: "행주 역사 이야기 전시",
        category: "전시",
        region: "고양시",
        address: "행주산성 역사공원",
        startDate: "2026-06-22",
        endDate: "2026-06-28",
        time: "10:00~17:00",
        price: "무료",
        image: "resources/hangju-festival.jpg",
        description: "지역 역사 자료와 주민 기록을 함께 소개하는 소규모 전시입니다.",
        transportInfo: "능곡역에서 마을버스 011번 이용",
        parkingInfo: "행주산성 주차장 이용 가능",
        nearbyStores: ["국수 거리", "전통찻집", "편의점"],
        applyLink: "#",
        contact: "031-222-5555",
        latitude: 37.6007,
        longitude: 126.8244,
        status: "approved"
    },
    {
        id: 6,
        title: "토마토 수확 체험",
        category: "체험",
        region: "광주시",
        address: "퇴촌면 체험 농장",
        startDate: "2026-06-23",
        endDate: "2026-06-24",
        time: "09:30~15:00",
        price: "10,000원",
        image: "resources/tomato-festival.jpg",
        description: "농가와 함께하는 토마토 수확 및 간단한 요리 체험 행사입니다.",
        transportInfo: "경기광주역에서 행사 셔틀버스 운행 예정",
        parkingInfo: "농장 임시 주차장 이용 가능",
        nearbyStores: ["농산물 직판장", "카페", "식당"],
        applyLink: "#",
        contact: "031-333-6666",
        latitude: 37.4717,
        longitude: 127.3054,
        status: "approved"
    },
    {
        id: 7,
        title: "유방동 작은 음악회",
        category: "공연",
        region: "용인시",
        address: "유방동 주민센터 앞마당",
        startDate: "2026-06-25",
        endDate: "2026-06-25",
        time: "18:30~20:00",
        price: "무료",
        image: "resources/eubang-festival.jpg",
        description: "주민 밴드와 청소년 동아리가 함께 만드는 야외 음악회입니다.",
        transportInfo: "용인터미널에서 버스 10번 이용",
        parkingInfo: "주민센터 주차 공간 협소",
        nearbyStores: ["동네 카페", "치킨집", "편의점"],
        applyLink: "#",
        contact: "031-444-7777",
        latitude: 37.2344,
        longitude: 127.2043,
        status: "approved"
    },
    {
        id: 8,
        title: "호수공원 주말 그림 전시",
        category: "전시",
        region: "고양시",
        address: "일산호수공원 산책로",
        startDate: "2026-06-26",
        endDate: "2026-06-27",
        time: "12:00~18:00",
        price: "무료",
        image: "resources/lake-festival.png",
        description: "지역 작가와 학생들이 참여하는 야외 그림 전시입니다.",
        transportInfo: "정발산역 도보 10분",
        parkingInfo: "호수공원 제2공영주차장 이용 가능",
        nearbyStores: ["카페 거리", "라페스타", "편의점"],
        applyLink: "#",
        contact: "031-555-8888",
        latitude: 37.6539,
        longitude: 126.7682,
        status: "approved"
    }
];
